version:     "August 2021"
copyright:   "2021-2021"
description:
  Operating System Assignment
keywords:    "jekyll, testing, os"
title:       "OS212"
lang:        "en-US"
author:      "Hakim Amarullah"
address:     "NONE"
sitemap:     "true"
github:
  - metadata
plugins:
  - jekyll-sitemap
urlweb:           "https://template.vlsm.org/"
urlgithub:        "https://github.com/hakimamarullah"


